# Generated by Django 5.2.6 on 2025-09-16 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jersey & Apparel', 'Jersey & Apparel'), ('Sepatu Bola', 'Sepatu Bola'), ('Peralatan & Perlengkapan', 'Peralatan & Perlengkapan'), ('Aksesoris & Merchandise', 'Aksesoris & Merchandise')], default='update', max_length=30),
        ),
    ]
